### ISSUE TITLE
Is there support for adding NS records to our DNS servers? 

### ISSUE THREAD

**Issue by ishneetdua** [Shopify/terraform-provider-dns#8]
We are currently using the nsupdate command to add NS records to our DNS servers. We generate a zone in Route53 and the NS records associated with that zone is what we want to add to our servers. We were trying to find a provider that can help with that. This provider adds A, Cname and text records but not NS (correct me if I am wrong-- very new to Terraform)? Are you guys working on NS records ?

**Comment by anuiq** [comment]
Unsupported.
